#!/usr/bin/env bash
# Install every Kilix terminal utility as a command.
#
# One installer for the whole set, replacing the per-project installers Kilix
# carried for kilix-temps and kilix-memory. Each command is a small launcher
# that runs the tool from this checkout, so an update is a git pull rather than
# a reinstall, and the checkout stays the single source of truth.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${KILIX_TUI_UTILS_PREFIX:-$HOME/.local}"
BIN="$PREFIX/bin"

# tool directory : installed command name
TOOLS=(
    "calculator:kilix-calculator"
    "cpu:kilix-cpu"
    "memory:kilix-memory"
    "disk:kilix-disk"
    "system:kilix-system"
    "volume:kilix-volume"
    "file:kilix-file"
    "package:kilix-package"
    "rollout_resume:kilix-rollout-resume"
    "session_log:kilix-session-log"
    "switcher:kilix-switch"
    "weather:kilix-weather"
    "music:kilix-music"
    "plebian_control:plebian-os"
)

die() { printf 'kilix-tui-utils: %s\n' "$1" >&2; exit 1; }

case "${PREFIX}" in
    /*) ;;
    *) die "KILIX_TUI_UTILS_PREFIX must be an absolute path" ;;
esac

command -v python3 >/dev/null 2>&1 || die "python3 is required"

mkdir -p "$BIN" || die "could not create $BIN"

installed=0
for entry in "${TOOLS[@]}"; do
    directory="${entry%%:*}"
    command_name="${entry##*:}"
    target="$HERE/tools/$directory/main.py"
    [ -f "$target" ] || { printf '  skip %s (missing)\n' "$command_name"; continue; }
    launcher="$BIN/$command_name"
    tmp="$launcher.tmp.$$"
    cat >"$tmp" <<LAUNCHER
#!/bin/sh
# Generated by kilix-tui-utils/install.sh — edits belong in the checkout.
exec python3 "$target" "\$@"
LAUNCHER
    chmod 0755 "$tmp"
    mv -f "$tmp" "$launcher"
    installed=$((installed + 1))
done

# The desktop is not in tools/ — it composes them — but installs the same way.
desktop_target="$HERE/kilix-tui/main.py"
if [ -f "$desktop_target" ]; then
    launcher="$BIN/kilix-tui"
    tmp="$launcher.tmp.$$"
    cat >"$tmp" <<LAUNCHER
#!/bin/sh
# Generated by kilix-tui-utils/install.sh — edits belong in the checkout.
exec python3 "$desktop_target" "\$@"
LAUNCHER
    chmod 0755 "$tmp"
    mv -f "$tmp" "$launcher"
    installed=$((installed + 1))
fi

printf 'kilix-tui-utils: installed %d commands into %s\n' "$installed" "$BIN"

# Kilix-95 builds its Start menu from XDG application entries. Sync them here so
# a fresh install shows up in the menu, and so the per-agent update entries match
# which coding agents are actually present on this machine.
if [ -f "$HERE/tools/rollout_resume/main.py" ]; then
    if python3 "$HERE/tools/rollout_resume/main.py" sync-menu >/dev/null 2>&1; then
        printf 'kilix-tui-utils: synced Kilix-95 start-menu entries\n'
    else
        printf 'kilix-tui-utils: note — could not sync start-menu entries\n'
    fi
fi

case ":$PATH:" in
    *":$BIN:"*) ;;
    *) printf 'kilix-tui-utils: note — %s is not on PATH\n' "$BIN" ;;
esac
