#!/usr/bin/env bash
# Install every Kilix terminal utility as a command.
#
# One installer for the whole set, replacing the per-project installers Kilix
# carried for kilix-temps and kilix-memory. Each command is a small launcher
# that runs the tool from this checkout, so an update is a git pull rather than
# a reinstall, and the checkout stays the single source of truth.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${KILIX_TUI_UTILS_PREFIX:-$HOME/.local}"
BIN="$PREFIX/bin"
RELOCATABLE="${KILIX_TUI_UTILS_RELOCATABLE:-0}"

# tool directory : installed command name
TOOLS=(
    "calculator:kilix-calculator"
    "cpu:kilix-cpu"
    "temps:kilix-temps"
    "memory:kilix-memory"
    "disk:kilix-disk"
    "system:kilix-system"
    "volume:kilix-volume"
    "network:kilix-network"
    "file:kilix-file"
    "launcher:kilix-launcher"
    "package:kilix-package"
    "rollout_resume:kilix-rollout-resume"
    "session_log:kilix-session-log"
    "switcher:kilix-switch"
    "weather:kilix-weather"
    "cameras:kilix-cameras"
    "music:kilix-music"
    "character_map:kilix-character-map"
    "find_files:kilix-find-files"
    "notepad:kilix-notepad"
    "plebian_control:plebian-os"
)

# Standalone applications that compose the shared core but are not desktop
# utilities under tools/.
APPLICATIONS=(
    "kilix-virtualbox-manager:kilix-virtualbox-manager"
)

# command name : focused application route in the shared desktop state
CENTERS=(
    "kilix-system-center:system"
    "kilix-settings-center:settings"
    "kilix-software-center:software"
    "kilix-session-center:session"
    "kilix-voice-studio:voice"
)

die() { printf 'kilix-tui-utils: %s\n' "$1" >&2; exit 1; }

write_launcher() {
    local target="$1" launcher="$2" command_name tmp word escaped relative
    shift 2
    command_name="${launcher##*/}"
    tmp="$(mktemp "$BIN/.${command_name}.XXXXXX")" \
        || die "could not create a temporary launcher in $BIN"
    # A POSIX single-quoted word represents every checkout path after each
    # literal quote is closed, escaped, and reopened.  This keeps spaces and
    # shell metacharacters in a clone path as data in the generated launcher.
    if ! {
        printf '%s\n' '#!/bin/sh'
        printf '%s\n' '# Generated by kilix-tui-utils/install.sh — edits belong in the checkout.'
        if [ "$RELOCATABLE" = 1 ]; then
            case "$target" in
                "$HERE"/*) relative="${target#"$HERE"/}" ;;
                *) die "relocatable launcher target is outside the checkout" ;;
            esac
            # The content installer builds under a randomly named staging
            # checkout and then renames the whole tree into place. Resolve the
            # selected checkout from .runtime/bin at launch time so that rename
            # cannot strand the wrapper at the deleted staging path.
            printf '%s\n' 'BIN_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)" || exit 1'
            printf '%s\n' 'CHECKOUT="$(CDPATH= cd -- "$BIN_DIR/../.." && pwd -P)" || exit 1'
            printf '%s' 'exec python3 "$CHECKOUT"/'
            escaped="${relative//\'/\'\\\'\'}"
            printf "'%s' " "$escaped"
        else
            printf '%s' 'exec python3 '
            escaped="${target//\'/\'\\\'\'}"
            printf "'%s' " "$escaped"
        fi
        for word in "$@"; do
            escaped="${word//\'/\'\\\'\'}"
            printf "'%s' " "$escaped"
        done
        printf '%s\n' '"$@"'
    } >"$tmp"; then
        rm -f -- "$tmp"
        die "could not write temporary launcher for $command_name"
    fi
    chmod 0755 "$tmp" || {
        rm -f -- "$tmp"
        die "could not make $command_name executable"
    }
    # os.replace has the rename semantics we need on every supported host:
    # it atomically replaces a file or symlink instead of treating a symlink
    # to a directory as a destination to descend into (as some mv variants
    # do without a non-portable -T flag).
    python3 -c 'import os, sys; os.replace(sys.argv[1], sys.argv[2])' \
        "$tmp" "$launcher" || {
        rm -f -- "$tmp"
        die "could not install $launcher"
    }
}

case "${PREFIX}" in
    /*) ;;
    *) die "KILIX_TUI_UTILS_PREFIX must be an absolute path" ;;
esac

case "$RELOCATABLE" in
    0|1) ;;
    *) die "KILIX_TUI_UTILS_RELOCATABLE must be 0 or 1" ;;
esac

command -v python3 >/dev/null 2>&1 || die "python3 is required"

if [ -L "$BIN" ]; then
    die "refusing symlinked install directory: $BIN"
fi
mkdir -p "$BIN" || die "could not create $BIN"
[ -d "$BIN" ] || die "install directory is not a directory: $BIN"

installed=0
for entry in "${TOOLS[@]}"; do
    directory="${entry%%:*}"
    command_name="${entry##*:}"
    target="$HERE/tools/$directory/main.py"
    [ -f "$target" ] || { printf '  skip %s (missing)\n' "$command_name"; continue; }
    launcher="$BIN/$command_name"
    write_launcher "$target" "$launcher"
    installed=$((installed + 1))
done

for entry in "${APPLICATIONS[@]}"; do
    directory="${entry%%:*}"
    command_name="${entry##*:}"
    target="$HERE/$directory/main.py"
    [ -f "$target" ] || { printf '  skip %s (missing)\n' "$command_name"; continue; }
    launcher="$BIN/$command_name"
    write_launcher "$target" "$launcher"
    installed=$((installed + 1))
done

# The desktop is not in tools/ — it composes them — but installs the same way.
desktop_target="$HERE/kilix-tui/main.py"
if [ -f "$desktop_target" ]; then
    launcher="$BIN/kilix-tui"
    write_launcher "$desktop_target" "$launcher"
    installed=$((installed + 1))
    for entry in "${CENTERS[@]}"; do
        command_name="${entry%%:*}"
        app_name="${entry##*:}"
        launcher="$BIN/$command_name"
        write_launcher "$desktop_target" "$launcher" --app "$app_name"
        installed=$((installed + 1))
    done
fi

printf 'kilix-tui-utils: installed %d commands into %s\n' "$installed" "$BIN"

# Kilix-95 builds its Start menu from XDG application entries. Sync them here so
# a fresh install shows up in the menu, and so the per-agent update entries match
# which coding agents are actually present on this machine.
if [ "${KILIX_TUI_UTILS_SYNC_MENU:-1}" != "0" ] && \
        [ -f "$HERE/tools/rollout_resume/main.py" ]; then
    if python3 "$HERE/tools/rollout_resume/main.py" sync-menu >/dev/null 2>&1; then
        printf 'kilix-tui-utils: synced Kilix-95 start-menu entries\n'
    else
        printf 'kilix-tui-utils: note — could not sync start-menu entries\n'
    fi
fi

case ":$PATH:" in
    *":$BIN:"*) ;;
    *) printf 'kilix-tui-utils: note — %s is not on PATH\n' "$BIN" ;;
esac
