"""Install or remove only the unified rollout-resume launcher.

The repository-wide ``install.sh`` remains the normal installer. These helpers
preserve the provider-specific tools' focused install/uninstall workflow for
users who only want session recovery.
"""
from __future__ import annotations

import os
from pathlib import Path
import shlex
import tempfile

from . import config, menu, providers

COMMAND = "kilix-rollout-resume"
MARKER = "Generated by kilix-tui-utils"


def default_bin_dir() -> Path:
    configured = os.environ.get("XDG_BIN_HOME")
    return (Path(configured).expanduser()
            if configured else Path.home() / ".local" / "bin")


def _managed_launcher(path: Path) -> bool:
    try:
        return MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _managed_desktop(path: Path) -> bool:
    try:
        return menu.MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def install_launcher(
    main_path: Path,
    *,
    bin_dir: Path | None = None,
    applications_dir: Path | None = None,
    force: bool = False,
) -> dict[str, object]:
    """Atomically install the command and managed desktop entries."""
    source = main_path.expanduser().resolve()
    if not source.is_file():
        raise RuntimeError(f"rollout-resume entry point is missing: {source}")
    binaries = (bin_dir or default_bin_dir()).expanduser()
    applications = (
        applications_dir or Path(menu.default_applications_dir())).expanduser()
    command = binaries / COMMAND
    desktop = applications / menu.PICKER
    if (command.exists() or command.is_symlink()) and not (
            force or _managed_launcher(command)):
        raise RuntimeError(f"refusing to replace unrelated command: {command}")
    if desktop.exists() and not (force or _managed_desktop(desktop)):
        raise RuntimeError(f"refusing to replace unrelated desktop entry: {desktop}")

    binaries.mkdir(mode=0o755, parents=True, exist_ok=True)
    applications.mkdir(mode=0o755, parents=True, exist_ok=True)
    script = (
        "#!/bin/sh\n"
        f"# {MARKER}/install-launcher\n"
        f"exec python3 {shlex.quote(str(source))} \"$@\"\n"
    )
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{COMMAND}.", dir=binaries)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(script)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(0o755)
        os.replace(temporary, command)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
    synced = menu.sync(
        providers.PROVIDERS, applications_dir=str(applications))
    config.write_config({})
    return {
        "command": str(command),
        "desktop_entry": str(desktop),
        "configuration": str(config.config_path()),
        "written": synced["written"],
    }


def uninstall_launcher(
    *,
    bin_dir: Path | None = None,
    applications_dir: Path | None = None,
) -> dict[str, object]:
    """Remove only managed launcher files, preserving user configuration."""
    binaries = (bin_dir or default_bin_dir()).expanduser()
    applications = (
        applications_dir or Path(menu.default_applications_dir())).expanduser()
    command = binaries / COMMAND
    removed: list[str] = []
    if (command.exists() or command.is_symlink()) and _managed_launcher(command):
        command.unlink()
        removed.append(str(command))
    removed.extend(menu.remove(
        providers.PROVIDERS, applications_dir=str(applications)))
    return {
        "removed": removed,
        "configuration": str(config.config_path()),
    }
